### ISSUE TITLE
Resolve the collector disk space issue

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/pipeline#265]
Collectors can reach disk space limits especially due to the uploads from legacy probes over Tor.

Historical data: https://mon.ooni.nu/grafana/d/AE8tFfxWk/collectors-disk-activity?orgId=1&from=1573488209215&to=1574697809215

Actions done:
-  [x] Running archiving script every hour
- [x] Set up onion services on every collector

What we are going to do:
* [x] Deploy 2 new hosts with 200GB disks to replace mia-ps & a new one in ams
* [x] Point the bouncer config on ams-ps to the new mia-ps and ams-ps
* [x] Once the spice is flowing to the new hosts deprecate mia-ps

200 GB * 2 should be enough storage for at least a few weeks of backlog even if the pipeline is stuck.

Long term action items:
- Investigate compressing reports asap (moved to: https://github.com/ooni/pipeline/issues/267)
- Investigate uploading reports to S3 or object storage asap (moved to: https://github.com/ooni/pipeline/issues/268)

**Comment by hellais** [comment]
What we are going to do:
* Deploy 2 new hosts with 200GB disks to replace mia-ps & a new one in ams
* Point the bouncer config on ams-ps to the new mia-ps and ams-ps
* Once the spice is flowing to the new hosts deprecate mia-ps

200 GB * 2 should be enough storage for at least a few weeks of backlog even if the pipeline is stuck.

**Comment by hellais** [comment]
Another thing that we should also not forget to look into is the reason why at some point we had a flatline in measurement data:

![Screenshot 2019-11-25 at 18 51 09](https://user-images.githubusercontent.com/424620/69565157-a67d9780-0fb4-11ea-95e1-d0cd30265d39.png)

The hypothesis is that it may have something to with the onion service collector not running properly.

**Comment by hellais** [comment]
These two:
* Improve monitoring around space usage and failed pipeline run and point to the pipeline handbook
*  Detect if we are receiving too few or too much data per hour

Have been moved into: https://github.com/ooni/sysadmin/issues/399

**Comment by hellais** [comment]
I have deployed two new hosts for this (`ams-ps2.ooni.nu` & `mia-ps2.ooni.nu` both with 200GB storage) and updated the bouncer config to:
```
collector:
  httpo://jehhrikjjqrlpufu.onion:
    collector-alternate:
    - {address: 'https://ams2-ps.ooni.nu:443', type: https}
    - {address: 'https://dkyhjv0wpi2dk.cloudfront.net', front: dkyhjv0wpi2dk.cloudfront.net, type: cloudfront}
    test-helper:
      dns: '{{ echo_th }}:57004'
      http-return-json-headers: 'http://{{ http_th }}:80'
      ssl: 'https://{{ echo_th }}'
      tcp-echo: {{ echo_th }}
      traceroute: {{ echo_th }}
      web-connectivity: 'httpo://o7mcp5y4ibyjkcgs.onion'
    test-helper-alternate:
      web-connectivity:
      - {address: 'https://ams-wcth.ooni.nu', type: https}
      - {address: 'https://d33d1gs9kpq1c5.cloudfront.net', front: d33d1gs9kpq1c5.cloudfront.net, type: cloudfront}
  httpo://hcn5nqahdkds6cjv.onion:
    collector-alternate:
    - {address: 'https://mia2-ps.ooni.nu:443', type: https}
    - {address: 'https://dkyhjv0wpi2dk.cloudfront.net', front: dkyhjv0wpi2dk.cloudfront.net, type: cloudfront}
    test-helper:
      dns: '{{ echo_th }}:57004'
      http-return-json-headers: 'http://{{ http_th }}:80'
      ssl: 'https://{{ echo_th }}'
      tcp-echo: {{ echo_th }}
      traceroute: {{ echo_th }}
      web-connectivity: 'httpo://o7mcp5y4ibyjkcgs.onion'
    test-helper-alternate:
      web-connectivity:
      - {address: 'https://ams-wcth.ooni.nu', type: https}
      - {address: 'https://d33d1gs9kpq1c5.cloudfront.net', front: d33d1gs9kpq1c5.cloudfront.net, type: cloudfront}
```
